version: "3.9"

services:
  app:
    image: node:22
    container_name: node_app
    working_dir: /usr/app
    volumes:
      - ./src:/usr/app/src
      - ./package.json:/usr/app/package.json
    ports:
      - "80:80"
    env_file:
      - ./.env
    command: sh -c "npm install && npm run dev"
    depends_on:
      - db
    networks:
      - app_net

  db:
    image: postgres:17
    container_name: postgres_db_node
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_net

volumes:
  postgres_data:

networks:
  app_net:
    driver: bridge
