version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: n8n_postgres
    restart: always
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8npass
      POSTGRES_DB: n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_app
    restart: always
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8npass

      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123

      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=America/Sao_Paulo

    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres

  localtunnel:
    image: node:18-alpine
    container_name: n8n_localtunnel
    restart: always
    depends_on:
      - n8n
    working_dir: /app
    network_mode: "service:n8n"
    command: sh -c "npm install -g localtunnel && lt --port 5678 --subdomain jonathantunel"
    # 👉 vai expor: https://jonathantunel.loca.lt

volumes:
  postgres_data:
  n8n_data: